improve namada docker images (#45)
* wip

* wip

* wip

* wip

diff --git a/masp-indexer/webserver/Dockerfile b/masp-indexer/webserver/Dockerfile
--- a/masp-indexer/webserver/Dockerfile
+++ b/masp-indexer/webserver/Dockerfile
@@ -2,6 +2,7 @@ FROM docker.io/rust:1.81-bookworm AS builder
 WORKDIR /app
 
 ARG GIT_SHA
+RUN [ -z "$GIT_SHA" ] && echo "GIT_SHA is required" && exit 1 || true
 
 RUN apt-get -y update && apt-get install -y make git-core libssl-dev pkg-config libclang-dev build-essential protobuf-compiler libudev-dev
 
diff --git a/namada/Dockerfile b/namada/Dockerfile
--- a/namada/Dockerfile
+++ b/namada/Dockerfile
@@ -2,10 +2,10 @@
 # Following the instruction from https://docs.namada.net/introduction/install/source
 # This is so we can do the localnet setup
 FROM docker.io/rust:1.81-slim-bookworm AS builder
+WORKDIR /namada
 
-# Pinning a release tag
 ARG GIT_SHA
-ARG PROFILE="release"
+RUN [ -z "$GIT_SHA" ] && echo "GIT_SHA is required" && exit 1 || true
 
 RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
     make \
@@ -22,10 +22,7 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-instal
     ca-certificates \
     && apt-get clean && rm -rf /var/lib/apt/lists/*
 
-ADD --keep-git-dir=true https://github.com/anoma/namada.git#$GIT_SHA /namada
-RUN cd /namada
-
-WORKDIR /namada
+ADD --keep-git-dir=true https://github.com/anoma/namada.git#$GIT_SHA .
 
 # Be aware the patch could potentially be version dependent
 # getting rid of the sudo
diff --git a/namada/Dockerfile.inst b/namada/Dockerfile.inst
--- a/namada/Dockerfile.inst
+++ b/namada/Dockerfile.inst
@@ -3,9 +3,8 @@
 # podman build --no-cache -t namada:v0.31.10-inst -f Dockerfile.inst .
 FROM docker.io/rust:1.81-slim-bookworm AS builder
 
-# Pinning a release tag
 ARG GIT_SHA
-ARG PROFILE="release"
+RUN [ -z "$GIT_SHA" ] && echo "GIT_SHA is required" && exit 1 || true
 
 WORKDIR /namada
 
@@ -22,10 +21,7 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-instal
     wget \
     && apt-get clean && rm -rf /var/lib/apt/lists/*
 
-ADD --keep-git-dir=true https://github.com/anoma/namada.git#$GIT_SHA /namada
-RUN cd /namada
-
-WORKDIR /namada
+ADD --keep-git-dir=true https://github.com/anoma/namada.git#$GIT_SHA .
 
 # Be aware the patch could potentially be version dependent
 # getting rid of the sudo
@@ -35,7 +31,7 @@ RUN git apply scripts_get_cometbft.patch
 # Instrumentation steps
 RUN wget -O /usr/lib/libvoidstar.so https://antithesis.com/assets/instrumentation/libvoidstar.so
 
-ENV RUSTFLAGS="-C passes=sancov-module \
+ENV RUSTFLAGS="-g -C passes=sancov-module \
 -Cllvm-args=-sanitizer-coverage-level=3 \
    -Cllvm-args=-sanitizer-coverage-trace-pc-guard \
    -Clink-args=-Wl,--build-id -Ccodegen-units=1 \
@@ -43,11 +39,14 @@ ENV RUSTFLAGS="-C passes=sancov-module \
 
 RUN make cometbft
 
-# RUN LD_LIBRARY_PATH=/usr/lib/libvoidstar.so cargo build --workspace --exclude namada_benchmarks
-RUN LD_LIBRARY_PATH=/usr/lib/libvoidstar.so cargo build --bin namadan
+RUN LD_LIBRARY_PATH=/usr/lib/libvoidstar.so cargo build --release --package namada_apps \
+    --manifest-path Cargo.toml \
+    --no-default-features \
+    --features jemalloc \
+    --features migrations
 
-# We built the profile in the debug, make it consistent with the make install
-RUN mv /namada/target/debug /namada/target/release
+RUN ldd target/release/namada | grep "libvoidstar"
+RUN nm target/release/namada | grep "sanitizer_cov_trace_pc_guard"
 
 RUN mkdir -p /root/.masp-params \
     && curl -o /root/.masp-params/masp-spend.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-spend.params?raw=true \
@@ -55,7 +54,7 @@ RUN mkdir -p /root/.masp-params \
     && curl -o /root/.masp-params/masp-convert.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-convert.params?raw=true
 
 # Try to slim down the runner
-FROM docker.io/rust:1.81-slim-bullseye
+FROM docker.io/rust:1.81-slim-bookworm
 
 RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
     ca-certificates \
